# Generated by Django 5.2.1 on 2025-05-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MineralPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element", models.CharField(max_length=50)),
                ("hardness", models.FloatField()),
                ("density", models.FloatField()),
                ("refractive_index", models.FloatField(blank=True, null=True)),
                ("predicted_group", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
