# Generated by Django 5.2.1 on 2025-05-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerals_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mineralprediction",
            old_name="density",
            new_name="calculated_density",
        ),
        migrations.RenameField(
            model_name="mineralprediction",
            old_name="hardness",
            new_name="mohs_hardness",
        ),
        migrations.AddField(
            model_name="mineralprediction",
            name="optical",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mineralprediction",
            name="specific_gravity",
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
