# Generated by Django 5.2.1 on 2025-05-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "minerals_api",
            "0002_rename_density_mineralprediction_calculated_density_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RockPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rock_images/")),
                ("predicted_class", models.CharField(max_length=100)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
